apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: dev
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 31000
  selector:
    module: frontend     